name: CI/CD Pipeline

on:
  push:
    branches:
      - AJKTest-Java

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: mvn package -f ./pom.xml

      - name: Build Docker image
        run: docker build -t ajithdevops/image-${{github.run_number}} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAMES }}
          password: ${{ secrets.DOCKERHUB_PASSWORDS }}

      - name: Push Docker image to Docker Hub
        run: docker image push ajithdevops/image-${{github.run_number}}

      - name: Installation of minikube and kubectl
        run: |
          curl -LO 'https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl'
          curl -LO "https://dl.k8s.io/v1.22.0/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          sudo apt-get update
          sudo apt install conntrack
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          sudo sysctl net/netfilter/nf_conntrack_max=524288
          minikube start

      - name: Deploy into kubernetes
        run: |
          kubectl create deployment kubetrialdeploy --image=ajithdevops/image-${{github.run_number}}  --replicas=3
          kubectl get deployments
          minikube dashboard
  notifications:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ajith.kumar29@wipro.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Deployment successful!
          body: The deployment was successful.
          to: ajith.kumar29@wipro.com
          from: ajith.kumar29@wipro.com
